### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Floof16** [Floof16/Tafe18S201#2]
So i've made a connection to the database in my PersonalInformation.cs but i keep getting an error in my Results() Method in my Views.PersonalInfo.xaml.cs if anyone could clone my recent push and have a look for me i'm finding it difficult sourcing solutions on google, does anyone know what i'm doing wrong? HELP PLEASE 🥇 💯

**Comment by matindi** [comment]
Add the connection string present in the newPage method onto the Results method. 
This will address the scope issue you've raised.

**Comment by Floof16** [comment]
problem solved
