### ISSUE TITLE
Personal info inability to edit a record

### ISSUE THREAD

**Issue by matindi** [Floof16/Tafe18S201#4]
Hey @Floof16 . I noticed that one's unable to edit a saved record on your code. 
Also, could you try saving two different records successively?(With different ids of course...)..I'm unable to save them that way. I have to close down the app to save a new record.

**Comment by Floof16** [comment]
ah thank you matindi, yeh seems i have a few issues with my code, thank you for pointing it out. i'm gonna have a look at where i've gone wrong now.

**Comment by Floof16** [comment]
issue solved. had "firstName" as unique when it should not have been.
